# Generated by Django 6.0.2 on 2026-02-26 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('jira_board_id', models.IntegerField(unique=True)),
                ('jira_project_key', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_sprint_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=300)),
                ('state', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('future', 'Future')], max_length=10)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('complete_date', models.DateTimeField(blank=True, null=True)),
                ('committed_points', models.FloatField(default=0)),
                ('completed_points', models.FloatField(default=0)),
                ('committed_count', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0)),
                ('added_during_sprint', models.IntegerField(default=0)),
                ('removed_during_sprint', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='forecaster.team')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_key', models.CharField(max_length=50, unique=True)),
                ('summary', models.CharField(max_length=500)),
                ('issue_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('done', 'Done')], default='todo', max_length=20)),
                ('story_points', models.FloatField(blank=True, null=True)),
                ('assignee', models.CharField(blank=True, max_length=200)),
                ('priority', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('cycle_time_hours', models.FloatField(blank=True, null=True)),
                ('lead_time_hours', models.FloatField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='forecaster.sprint')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='forecaster.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_items', models.IntegerField(help_text='Number of items to forecast completion for')),
                ('sprint_length_days', models.IntegerField(default=14)),
                ('simulations', models.IntegerField(default=10000)),
                ('history_days', models.IntegerField(default=90)),
                ('p50_sprints', models.FloatField(help_text='50th percentile — sprints needed')),
                ('p70_sprints', models.FloatField(help_text='70th percentile')),
                ('p85_sprints', models.FloatField(help_text='85th percentile')),
                ('p95_sprints', models.FloatField(help_text='95th percentile')),
                ('p50_days', models.FloatField()),
                ('p70_days', models.FloatField()),
                ('p85_days', models.FloatField()),
                ('p95_days', models.FloatField()),
                ('avg_throughput_per_sprint', models.FloatField()),
                ('std_throughput_per_sprint', models.FloatField()),
                ('raw_results', models.JSONField(default=dict, help_text='Full simulation histogram data')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='forecaster.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThroughputSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('items_completed', models.IntegerField(default=0)),
                ('points_completed', models.FloatField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='throughput_snapshots', to='forecaster.team')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('team', 'date')},
            },
        ),
    ]
